-- Bank schema and synthetic import generated by delivered Step 17 (4971d13).
CREATE TABLE bank_accounts (
            entity_id TEXT PRIMARY KEY, bank_account_id TEXT NOT NULL,
            ledger_account TEXT NOT NULL CHECK(ledger_account='1000') REFERENCES accounts(code),
            currency TEXT NOT NULL CHECK(currency='USD'), synthetic INTEGER NOT NULL CHECK(synthetic=1),
            actor_id TEXT NOT NULL, recorded_at TEXT NOT NULL,
            UNIQUE(entity_id,bank_account_id)) STRICT, WITHOUT ROWID;
CREATE TABLE bank_membership (
            entity_id TEXT NOT NULL, bank_account_id TEXT NOT NULL, statement_id TEXT NOT NULL,
            row_number INTEGER NOT NULL CHECK(row_number BETWEEN 1 AND 100), transaction_id TEXT NOT NULL,
            PRIMARY KEY(entity_id,bank_account_id,statement_id,row_number),
            UNIQUE(entity_id,bank_account_id,statement_id,transaction_id),
            FOREIGN KEY(entity_id,bank_account_id,statement_id) REFERENCES bank_statements(entity_id,bank_account_id,statement_id),
            FOREIGN KEY(entity_id,bank_account_id,transaction_id) REFERENCES bank_transactions(entity_id,bank_account_id,transaction_id)) STRICT, WITHOUT ROWID;
CREATE TABLE bank_receipts (
            entity_id TEXT NOT NULL, bank_account_id TEXT NOT NULL, statement_id TEXT NOT NULL, audit_json TEXT NOT NULL,
            PRIMARY KEY(entity_id,bank_account_id,statement_id),
            FOREIGN KEY(entity_id,bank_account_id,statement_id) REFERENCES bank_statements(entity_id,bank_account_id,statement_id)) STRICT, WITHOUT ROWID;
CREATE TABLE bank_schema (version INTEGER PRIMARY KEY CHECK(version=1)) STRICT, WITHOUT ROWID;
CREATE TABLE bank_statements (
            entity_id TEXT NOT NULL, bank_account_id TEXT NOT NULL, statement_id TEXT NOT NULL,
            content_digest TEXT NOT NULL, statement_json TEXT NOT NULL,
            PRIMARY KEY(entity_id,bank_account_id,statement_id),
            FOREIGN KEY(entity_id,bank_account_id) REFERENCES bank_accounts(entity_id,bank_account_id),
            FOREIGN KEY(entity_id,bank_account_id,statement_id) REFERENCES bank_receipts(entity_id,bank_account_id,statement_id)
                DEFERRABLE INITIALLY DEFERRED) STRICT, WITHOUT ROWID;
CREATE TABLE bank_transactions (
            entity_id TEXT NOT NULL, bank_account_id TEXT NOT NULL, transaction_id TEXT NOT NULL,
            amount_cents INTEGER NOT NULL CHECK(amount_cents!=0), row_json TEXT NOT NULL,
            actor_id TEXT NOT NULL, recorded_at TEXT NOT NULL,
            PRIMARY KEY(entity_id,bank_account_id,transaction_id),
            FOREIGN KEY(entity_id,bank_account_id) REFERENCES bank_accounts(entity_id,bank_account_id)) STRICT, WITHOUT ROWID;
INSERT INTO bank_accounts VALUES('demo-service-001','fictional-bank','1000','USD',1,'legacy-operator','2026-10-08T16:57:04.407021+00:00');
INSERT INTO bank_membership VALUES('demo-service-001','fictional-bank','legacy-statement',1,'legacy-deposit');
INSERT INTO bank_receipts VALUES('demo-service-001','fictional-bank','legacy-statement','{"actor_id":"legacy-operator","content_digest":"48ddda0dd86538c06badca850c6d529179f911da5119a5a77a6628c42fe69166","receipt_id":"bank-import-583820b1d6c49a8c49db1cbee1663e14cfa7da6b3a7a54e48da50f397cfae053","recorded_at":"2026-10-08T16:57:04.407021+00:00","source_digest":"8322d89f2dc484475f11fa62437c57913ba3caa98b55c0fad1daf548d9f22b23"}');
INSERT INTO bank_schema VALUES(1);
INSERT INTO bank_statements VALUES('demo-service-001','fictional-bank','legacy-statement','48ddda0dd86538c06badca850c6d529179f911da5119a5a77a6628c42fe69166','{"bank_account_id":"fictional-bank","closing_balance":"200.00","currency":"USD","entity_id":"demo-service-001","ledger_account":"1000","movement_total":"200.00","opening_balance":"0.00","period_end":"2026-01-31","period_start":"2026-01-01","row_count":1,"source_digest":"8322d89f2dc484475f11fa62437c57913ba3caa98b55c0fad1daf548d9f22b23","statement_id":"legacy-statement","synthetic":true}');
INSERT INTO bank_transactions VALUES('demo-service-001','fictional-bank','legacy-deposit',20000,'{"amount":"200.00","amount_cents":20000,"bank_account_id":"fictional-bank","booking_date":"2026-01-05","currency":"USD","description":"Fictional legacy movement","reference":"","transaction_id":"legacy-deposit"}','legacy-operator','2026-10-08T16:57:04.407021+00:00');
CREATE TRIGGER bank_accounts_no_delete BEFORE DELETE ON bank_accounts
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_accounts_no_replace BEFORE INSERT ON bank_accounts
        WHEN EXISTS (SELECT 1 FROM bank_accounts WHERE entity_id=NEW.entity_id)
        BEGIN SELECT RAISE(ABORT, 'review records cannot be replaced'); END;
CREATE TRIGGER bank_accounts_no_update BEFORE UPDATE ON bank_accounts
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_membership_no_delete BEFORE DELETE ON bank_membership
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_membership_no_replace BEFORE INSERT ON bank_membership
        WHEN EXISTS (SELECT 1 FROM bank_membership WHERE entity_id=NEW.entity_id AND bank_account_id=NEW.bank_account_id
                AND statement_id=NEW.statement_id AND (row_number=NEW.row_number OR transaction_id=NEW.transaction_id))
        BEGIN SELECT RAISE(ABORT, 'review records cannot be replaced'); END;
CREATE TRIGGER bank_membership_no_update BEFORE UPDATE ON bank_membership
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_membership_sealed BEFORE INSERT ON bank_membership
            WHEN EXISTS (SELECT 1 FROM bank_receipts WHERE entity_id=NEW.entity_id
                AND bank_account_id=NEW.bank_account_id AND statement_id=NEW.statement_id)
            BEGIN SELECT RAISE(ABORT,'statement membership is sealed'); END;
CREATE TRIGGER bank_receipts_no_delete BEFORE DELETE ON bank_receipts
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_receipts_no_replace BEFORE INSERT ON bank_receipts
        WHEN EXISTS (SELECT 1 FROM bank_receipts WHERE entity_id=NEW.entity_id AND bank_account_id=NEW.bank_account_id AND statement_id=NEW.statement_id)
        BEGIN SELECT RAISE(ABORT, 'review records cannot be replaced'); END;
CREATE TRIGGER bank_receipts_no_update BEFORE UPDATE ON bank_receipts
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_schema_no_delete BEFORE DELETE ON bank_schema
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_schema_no_replace BEFORE INSERT ON bank_schema
        WHEN EXISTS (SELECT 1 FROM bank_schema WHERE 1)
        BEGIN SELECT RAISE(ABORT, 'review records cannot be replaced'); END;
CREATE TRIGGER bank_schema_no_update BEFORE UPDATE ON bank_schema
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_statements_no_delete BEFORE DELETE ON bank_statements
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_statements_no_replace BEFORE INSERT ON bank_statements
        WHEN EXISTS (SELECT 1 FROM bank_statements WHERE entity_id=NEW.entity_id AND bank_account_id=NEW.bank_account_id AND statement_id=NEW.statement_id)
        BEGIN SELECT RAISE(ABORT, 'review records cannot be replaced'); END;
CREATE TRIGGER bank_statements_no_update BEFORE UPDATE ON bank_statements
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_transactions_no_delete BEFORE DELETE ON bank_transactions
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
CREATE TRIGGER bank_transactions_no_replace BEFORE INSERT ON bank_transactions
        WHEN EXISTS (SELECT 1 FROM bank_transactions WHERE entity_id=NEW.entity_id AND bank_account_id=NEW.bank_account_id AND transaction_id=NEW.transaction_id)
        BEGIN SELECT RAISE(ABORT, 'review records cannot be replaced'); END;
CREATE TRIGGER bank_transactions_no_update BEFORE UPDATE ON bank_transactions
            BEGIN SELECT RAISE(ABORT, 'review records are append-only'); END;
